// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22.10.2025, 09:04:07
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/demir/bluelock/blue/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/demir/bluelock/blue/frontend/composables/**/*.{js,ts,mjs}","C:/Users/demir/bluelock/blue/frontend/utils/**/*.{js,ts,mjs}","C:/Users/demir/bluelock/blue/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;