// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03.06.2025, 18:32:16
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/demir/bluelock/blue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/plugins/**/*.{js,ts,mjs}","C:/Users/demir/bluelock/blue/composables/**/*.{js,ts,mjs}","C:/Users/demir/bluelock/blue/utils/**/*.{js,ts,mjs}","C:/Users/demir/bluelock/blue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/demir/bluelock/blue/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;